# Site Settings
name                     : "Sakshi Sen"
description              : "B.Tech CSE | AI/ML • Full-Stack • Cloud | RTU 2027"
url                      : "https://sakshisen12.github.io"
baseurl                  : ""
repository               : "Sakshisen12/Sakshisen12.github.io"
github_username          : "Sakshisen12"

# Site Author
author:
  name             : "Sakshi Sen"
  avatar           : "/images/profile.png"
  bio              : "B.Tech CSE @ RTU | CGPA: 8.87 | AI/ML • DevOps • Full-Stack"
  location         : "Kota, Rajasthan, India"
  email            : "shakshisen35600@gmail.com"
  github           : "Sakshisen12"
  linkedin         : "www.linkedin.com/in/sakshi-sen123"
  uri              : "https://sakshisen12.github.io"

# Reading Files
include:
  - .htaccess
  - _pages

# Build Settings
markdown         : kramdown
highlighter      : rouge
permalink        : /:categories/:title/
paginate         : 5
paginate_path    : /page:num/
timezone         : Asia/Kolkata

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
